dist: bionic
language: generic
before_install:
# [WIP] attempting to run vagrant
  - cat /proc/cpuinfo
  - free -m
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - && sudo sh -c "echo deb https://download.virtualbox.org/virtualbox/debian bionic contrib >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get install build-essential gcc make linux-headers-$(uname -r) virtualbox-6.0 && sudo usermod -aG vboxusers $(whoami)
  - export VER="1.5.1"
  - wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
  - unzip packer_${VER}_linux_amd64.zip
  - sudo mv packer /usr/local/bin
  - packer --version
  - git clone https://github.com/ssmirr/bento.git
  - cd bento/packer_templates/ubuntu
  - travis_wait 45 packer build -only=virtualbox-iso ubuntu-18.04-amd64.json

env:
  global:
    secure: mFkLkmluJNcXLxBTymrFFFSVYeJbrjWBIRNUQCKvDjRol/4W0LUyTTHHd8YJmm/jte6IkqATXp475EhDEVRoh6txYDPH1cDPp6gzCfhy6Pn2dijZIJ1feYoqJLEhh5RccvItDHf4ZCMErNuPStmdkldBm2t3t/5SsfOPqHXjV0Lm2Zzdcxfmno6rtICJ2pTaEY24CDUm+B8r+uTvrNgk33A4aflxe2Jm5/0pxC4PVVPbRc9+XOy11+uqmO0o4UuVdBYpYZPdJiQ2E7/4w4xmDlqLMA2gRiX3WblMqGmi4BxWObU5PhYRcbTDysc7sPII4CBVa0v7rEddvs1O7ZVnTKf+EXFxWI+737iiDW6UZ2ZSa9flIhJeaP/ygwbMUZJZBX9kP1vPyF9mW6OdDoW/ZA6bQtixdWZEUQexva/3jz9LH5ZLtvfkZb6f1gWnhz+MhAqLTGvxu2+4K7PgAmzgqL4T0rBkpHeIl7sTCFm9rHd5R6iVrkzrcDU/sePkrBiu/GPxwgbE2S2ZM7dv57IlDD5CUMoBbfGw3g80mJdEDHvGEZ5EwvYnxfhpT4ysdEy1DFtpkyxr+9ffbRtt0bGwuQWLcF6+3eC9iBEHYzYxTB4A0UDc425nr5m2iiE7ixzfEz84uoB6R8j47Oyt95DMtyE3C7GIz1iD4I5wb7zwpDc=

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "travis"
  - git config --local user.email "ssmirr@noreply.github.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "$api_key"
  file: "../../builds/ubuntu-18.04.virtualbox.box"
  skip_cleanup: true
  overwrite: true
